---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: network-traffic-meter
  namespace: kiada
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'quay.io/maciek01220/network-traffic-meter:0.1'
    pushSecret:
      name: maciek01220-quay-push-pull-secret
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      forcePull: true
  postCommit: {}
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/maciek01170/kubernetes-in-action-2nd-edition.git'
      ref: 'training/202507'
    contextDir: /Chapter05/network-traffic-meter-0.1

  runPolicy: Serial
