apiVersion: v1
kind: Pod
metadata:
  name: kiada-init
spec:
  initContainers:
  - name: init-demo
    image: quay.io/maciek01220/init-demo:0.1
    imagePullPolicy: Always
  - name: network-check
    image: quay.io/maciek01220/network-connectivity-checker:0.1
    imagePullPolicy: Always
  containers:
  - name: kiada
    image: quay.io/maciek01220/kiada:0.2
    stdin: true
    ports:
    - name: http
      containerPort: 8080
  - name: envoy
    image: quay.io/maciek01220/kiada-ssl-proxy:0.1
    imagePullPolicy: Always
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901
    env:
      - name: ENVOY_UID
        value: '0'

